### ISSUE TITLE
Need a way to link PHP client version with Google AdWords API version

### ISSUE THREAD

**Issue by starrychloe** [googleads/googleads-php-lib#102]
How do we know that version 6.5 of the PHP client implements 201509 of the API version? There should be a table which shows the PHP client version and the API version that it implements.

**Comment by fiboknacky** [comment]
Hello,

Everything about support or removal of API versions is listed up at [releases](https://github.com/googleads/googleads-php-lib/releases).
You can see that since v6.4.0 we provide support for v201509 of AdWords API.

In addition, you can also explore the [AdWords/](https://github.com/googleads/googleads-php-lib/tree/master/src/Google/Api/Ads/AdWords) folder directly to see if it contains a folder of v201509.
