### ISSUE TITLE
Class 'ReportUtils'  not found.

### ISSUE THREAD

**Issue by DenisOgr** [googleads/googleads-php-lib#113]
Hi.
I use this library with composer. After composer update (20.01.2016) I have begun get errors "Class 'ReportUtils'  not found."
I used this class:
```
\ReportUtils::DownloadReportWithAwql();
```

I read that you have added version for this ReportUtils, but it does not work with composer (with autoload).
PS: I use v201506 version.
Can you solve this problem?

**Comment by coodix** [comment]
My solution is to add next class mapping into autoload block in composer.json:
```
"classmap": [
            "vendor/googleads/googleads-php-lib/src/Google/Api/Ads/AdWords/Util/v201509"
        ]
```

Suppose in your case you need to replace v201509 with v201506.

**Comment by DenisOgr** [comment]
@coodix thanks, I think, it will be work, but I think, i bad way. It need to fix in repository.

**Comment by fiboknacky** [comment]
Hi,

Thanks for reporting.
I'll look into this soon.

**Comment by fiboknacky** [comment]
Hello,

We decided not to modify composer.json in this branch.
This is because it requires us to change all underlying classes in [Util](https://github.com/googleads/googleads-php-lib/tree/master/src/Google/Api/Ads/AdWords/Util) to have a namespace, which makes the lib in an inconsistent state (only some have namespaces).

We've updated the workaround in the [README.md](https://github.com/googleads/googleads-php-lib/blob/master/README.md) file.

However, we've just [announced the beta release](http://googleadsdeveloper.blogspot.jp/2016/02/announcing-beta-release-of-new-ads-php.html) of new PHP client lib with PSR-4 and namespace support.
You could try that branch [here](https://github.com/googleads/googleads-php-lib/tree/experimental). 

Best,
Knack
