### ISSUE TITLE
Feature request: revoke access token example

### ISSUE THREAD

**Issue by hakimio** [googleads/googleads-php-lib#115]
It would be nice if this library would provide revoke access token capability like the generic google API client library does: https://github.com/google/google-api-php-client/blob/master/src/Google/AccessToken/Revoke.php

**Comment by vtsao** [comment]
Thanks for the feedback, will keep this in mind.

**Comment by vtsao** [comment]
The beta version of this client library now uses the [Google Auth PHP library](https://github.com/google/google-auth-library-php), instead of this library having its own OAuth2 code. So please check out that library to see if they support this, or file a similar feature request.

We won't be adding any OAuth2 features to the current client library as we're focusing efforts on getting the beta version to stable). Please check out the [changelog](https://github.com/googleads/googleads-php-lib/blob/experimental/CHANGELOG.md) for details.
