### ISSUE TITLE
BC Math requirement

### ISSUE THREAD

**Issue by rik-coenders** [googleads/googleads-php-lib#156]
Version 10.1.0 uses the function bccomp (http://php.net/manual/en/function.bccomp.php) from BC Math in the file src\Google\Api\Ads\AdWords\Util\XmlSerializer.php
This function only works with BC Math enabled, which is not default in php. The requirement for BC Math is not documented in the README file, and seems unnecessary, because this problem could easily be solved in a way not requiring BC Math.

**Comment by fiboknacky** [comment]
Hello,

Sorry for late response.
I'll take a look as soon as possible.

Knack

**Comment by janakprajapati** [comment]
Hi Knack,

Any updates on the issue? or is there any alternate way which we can use to prevent the error?

Thanks,
Janak

**Comment by hakimio** [comment]
@janakprajapati 
bccomp is rather simple function. If you don't want or can't use PHP BC Math extension, you can simply introduce the function in your code:
http://pastebin.com/UCr4T8re

**Comment by fiboknacky** [comment]
Hi @janakprajapati 

The reason why we decided to use bccomp was because PHP doesn't handle some of the edge cases when numbers are so large correctly.
Therefore, we need more accurate computation for that.

I'll discuss with my colleague to see what it's the best in this case.
Sorry for your inconvenience.

@hakimio 
Thanks for your comment!

Knack

**Comment by fiboknacky** [comment]
Fixed in [v13.1.0](https://github.com/googleads/googleads-php-lib/releases/tag/13.1.0)
