### ISSUE TITLE
Use JSON instead of INI

### ISSUE THREAD

**Issue by swordbeta** [googleads/googleads-php-lib#185]
The Google API Manager allows you to download the client ID, client secret and other metadata. It would be nice if we'd be able to use this instead of the current ini file. https://github.com/google/google-api-php-client allows this.

**Comment by vtsao** [comment]
Hi @swordbeta can you clarify which class in the Google Auth client you are referring to that takes in a JSON file downloaded from the API Manager?

Alternatively, our library relies on the Google Auth library for OAuth2. You may use the Google Auth library directly if you wish to create an OAuth2 credential and pass it into our AdsSession object if you don't want to use the INI file for credential storage.

https://github.com/googleads/googleads-php-lib/blob/master/examples/Dfp/v201611/CompanyService/GetAllCompanies.php#L85

The `withOAuth2Credential` method in the ads session builders will take in an instance of [FetchAuthTokenInterface](https://github.com/google/google-auth-library-php/blob/master/src/FetchAuthTokenInterface.php), which is effectively a "credential" that is created by most flows in the Google Auth library.

Thanks,
Vincent

**Comment by ronoudgenoeg** [comment]
@vtsao [google-api-php-client](https://github.com/google/google-api-php-client) allows downloaded JSON credentials from Google API console to be used with the `Google_Client::setAuthConfig` method as seen [here](https://github.com/google/google-api-php-client#authentication-with-oauth).

**Comment by vtsao** [comment]
@ronoudgenoeg Thanks for the link. To clarify that's the Google PHP library, which is a separate library from the Google Auth PHP library (it uses the Google Auth PHP library). The link you provided is showing the initial OAuth2 dance/process of obtaining an access token. Our INI file is meant to be used when you've already obtained an offline refresh token. The JSON credentials you download from the API Manager will only contain a client ID and a client secret. You will still need to provide an offline refresh token to our library (if using installed application flow). That's why we provide a convenience to set OAuth2 client ID, secret, and refresh token in the INI file so it's all in one place.

Let me know if you have further questions on this. Thanks.
