### ISSUE TITLE
Polling a batch job via PHP library needs unnecessary upload URL?

### ISSUE THREAD

**Issue by komirad** [googleads/googleads-php-lib#189]
Posted this in the AdWords API forum here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/adwords-api/FA03p5HAVGE/s7Uo5WxjCwAJ

I noticed in the PHP library, BatchJobUtils' constructor has a required $uploadUrl param. Isn't upload URL unnecessary when polling a batch job?

In my case, I am using a queue system to poll the batch job.

Since I can't get the upload URL using BatchJobService->get (Doc says "This field is only returned when calling BatchJobService.mutate with an ADD operation."),

**it means that I have to store the redundant upload URL in my database. Please let me know if this is true.**

Sample code for downloading batch job results:
```
    $batchJobUtils = new \BatchJobUtils($batchJob->uploadUrl->url);
    if ($batchJob->downloadUrl !== null && $batchJob->downloadUrl->url !== null) {
        $xmlResponse = $batchJobUtils->DownloadBatchJobResults($batchJob->downloadUrl->url);
    }
```

Reading the Java sample code, instead of BatchJobUtils it's BatchJobHelper. BatchJobHelper does not have the required upload URL param.
```
AdWordsSession session = new AdWordsSession.Builder().fromFile().withOAuth2Credential(oAuth2Credential).build();
BatchJobHelper batchJobHelper = new BatchJobHelper(session);
batchJobHelper.downloadBatchJobMutateResponse(batchJob.getDownloadUrl().getUrl());
```

**Comment by fiboknacky** [comment]
Hello JC,

I think what's not convenient for you is the downloading results process, right?
(The polling of the results  is not related to `BatchJobUtils` itself)
If so, yes, the current version of `BatchJobUtils` does require an upload URL for initialization.
Sorry for this inconvenience.

This issue has been fixed in our [experimental branch](https://github.com/googleads/googleads-php-lib/tree/experimental).
Its [BatchJobs](https://github.com/googleads/googleads-php-lib/blob/experimental/src/Google/AdsApi/AdWords/BatchJobs/v201607/BatchJobs.php) now doesn't require an upload URL, and you can create it to just for [downloading batch job results](https://github.com/googleads/googleads-php-lib/blob/experimental/src/Google/AdsApi/AdWords/BatchJobs/v201607/BatchJobs.php#L241) as well.

The stable release progress of experimental branch is kept track in issue #4.

Cheers,
Knack
