### ISSUE TITLE
  Fatal error: Class 'Google\AdsApi\Common\OAuth2TokenBuilder' not found in 

### ISSUE THREAD

**Issue by hiakong** [googleads/googleads-php-lib#222]
I    install the library via Composer,  then I run the example , oh ,no  .

"Fatal error: Class 'Google\AdsApi\Common\OAuth2TokenBuilder' not found in /home/wwwroot/default/examples/AdWords/v201609/BasicOperations/AddCampaigns.php on line 176"   ,  then I check that "Google\AdsApi\Common\OAuth2TokenBuilder",  find that in the OAuth2TokenBuilder.php,  like this:

namespace Google\AdsApi\Common; 
use Google\Auth\Credentials\ServiceAccountCredentials;
use Google\Auth\Credentials\UserRefreshCredentials;
use Google\Auth\FetchAuthTokenInterface;
use InvalidArgumentException;

Oh ,no , there is no “Auth” folder in the  'Google' folder!!!!

**Comment by fiboknacky** [comment]
Hello @hiakong 

I'm sorry to hear that!
Could you please clarify the steps you used to install the library?
Did you follow [these steps](https://github.com/googleads/googleads-php-lib#getting-started)?

As for the error in the example that you mentioned, it shouldn't happen like that because  `OAuth2TokenBuilder` is explicitly imported in [this line](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201609/BasicOperations/AddCampaigns.php#L46).
If your downloaded code is different from that, could you please share your code here?

Best,
Knack

**Comment by hiakong** [comment]
@fiboknacky   I follow these steps you mentioned,  I  don't know why !  you just tell me that  is there the 'Auth' folder  in the 'Google' folder  when you  use  Composer

**Comment by hiakong** [comment]
@fiboknacky  you just via composer   again , you can  find the problem

**Comment by hiakong** [comment]
I fix  that !  thanks

**Comment by franklinfalves** [comment]
how did you fix this?

**Comment by leolll** [comment]
@franklinfalves That specific error should resolve if you include this line in your code:

`use Google\AdsApi\Common\OAuth2TokenBuilder;`
