### ISSUE TITLE
RateExceededError Example

### ISSUE THREAD

**Issue by nhtahoe** [googleads/googleads-php-lib#280]
Would be super helpful to have an example showing how to catch and handle RateExceededError.

**Comment by fiboknacky** [comment]
Hi @nhtahoe 

[HandlePolicyViolationError](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201702/ErrorHandling/HandlePolicyViolationError.php) shows how to catch an exception and handle based on the type of the exception.
You could adapt this to use with `RateExceededError` instead of `PolicyViolationError`.

Best,
Knack
