### ISSUE TITLE
Number of results found is Zero

### ISSUE THREAD

**Issue by fammejias1** [googleads/googleads-php-lib#281]
I've been using the old library fine for years.
I've decided to start testing the new library in preparation to migrate to it, so I have setup the new library and setup the adsapi_php.ini (with the same information from my old Auth.ini file).

However, When I run the tests now I am getting that the number of results found is zero as shown below:

PS D:\Dev\WSPHP\TestG\vendor\googleads\googleads-php-lib\examples\AdWords\v201702\BasicOperations> php GetCampaigns.php
Number of results found: 0

Now I am using the old library and with the same credentials, obviously configured in the proper auth.ini file and its working fine in production.

I am a little baffled as to why I am getting zero with the new library.

Any tips on what i can try to resolve this problem?

Again, my account credentials and tokens work perfectly fine in the old library.

**Comment by fiboknacky** [comment]
Hi @fammejias1 

Could you please give more information about your `adsapi_php.ini`, especially your client customer ID?
Thanks.

Knack

**Comment by fammejias1** [comment]
Sure here it is:
clientCustomerId = "279-808-7757"

**Comment by fiboknacky** [comment]
Hi @fammejias1 

That client customer ID is of a manager account, which doesn't possess any campaigns.
That's why you don't see anything returned.
Could you try setting the client customer ID to your client accounts, e.g., 286-864-83XX?

You can set the client customer ID by using [`withClientCustomerId()`](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php#L209)

Hope this help.

Best,
Knack

**Comment by fiboknacky** [comment]
Close this issue due to inactivity. Please let me know if you need further help.
