### ISSUE TITLE
Doesn't work with PHP 5.6

### ISSUE THREAD

**Issue by SeriousJ55** [googleads/googleads-php-lib#285]
Everything works fine when running the API with PHP version 7.0.9.

But I can't make it work with PHP version 5.6.30-0+deb8u1.

I get many different errors like this one:
`Fatal error: Uncaught SoapFault exception: [Client] Function ("get") is not a valid method for this service in /www/Libraries/googleads-php-lib-master/src/Google/AdsApi/Common/AdsSoapClient.php:116 Stack trace: #0 /www/Libraries/googleads-php-lib-master/src/Google/AdsApi/Common/AdsSoapClient.php(116): SoapClient->__soapCall('get', Array, NULL, Array, Array) #1 /www/Libraries/googleads-php-lib-master/src/Google/AdsApi/AdWords/v201702/cm/CampaignService.php(156): Google\AdsApi\Common\AdsSoapClient->__soapCall('get', Array) #2 /www/Includes/fonctions_adwords/GetCampaigns.php(41): Google\AdsApi\AdWords\v201702\cm\CampaignService->get(Object(Google\AdsApi\AdWords\v201702\cm\Selector)) #3 /www/test_fonctions.php(69): GetCampaigns(Object(Google\AdsApi\AdWords\AdWordsSession)) #4 {main} thrown in /www/Libraries/googleads-php-lib-master/src/Google/AdsApi/Common/AdsSoapClient.php on line 116`

I tried everything and nothing works with PHP version 5.6.30. Is there a fix?

**Comment by fiboknacky** [comment]
Hi @SeriousJ55 

Is this [article's](https://lornajane.net/posts/2015/soapfault-when-switching-php-versions) scenario similar to your case?
Switching between PHP v7 and v5.6 can cause such an issue because of the difference in WSDL caching.

Best,
Knack

**Comment by thomhickey** [comment]
Hello,

We seem to have a 5.6 problem. Everything works in 7. We cleared all wsdl caches, but we still get:

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
   <soap:Body>
      <soap:Fault>
         <faultcode>soap:Client</faultcode>
         <faultstring>Unmarshalling Error: 00:00:50Z</faultstring>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>

The criterion it's complaining about is a Proximity value that we're sending through CampaignCriterionService:

<ns1:radiusInUnits>00:00:50Z</ns1:radiusInUnits>

But the problem is we're setting that radius as 50 and somehow it comes out as '00:00:50Z' when we use php 5.6. Any ideas what is happening here? The same data run through php 7 works fine and we see:

<ns1:radiusInUnits>50</ns1:radiusInUnits>

in the logs and the mutation is successful. Really scratching our heads with this one. Also, if we force '00:00:50Z' into the radius value at runtime, we get back a clean CriterionError.INVALID_PROXIMITY_RADIUS from the server so we're pretty sure something gets munged on the way out.

AwApi-PHP, googleads-php-lib/25.4.0, PHP/5.6.27
v201702

Thanks in advance,
-Thom

**Comment by fiboknacky** [comment]
Hi Thom,

Could you please share the code portion that you use to create `Proximity` object (which include `radiusInUnits`), sent to CampaignCriterionService please?
It looks like there are some casting problems here.

I'm not 100% sure but there might be some difference between PHP 7 casting and PHP 5.6 casting mechanisms.

Best,
Knack

**Comment by thomhickey** [comment]
Hi Knack,

Sure, here's the code:

`        /**
         * returns spend areas as a CampaignCriterion array
         * @param int $campaign_id
         * @param array $spend_areas
         * @return array
         */
        public function spendsToCampaignCriteria( $campaign_id, $spend_areas )
        {
            $proximities = [];
            foreach ( $spend_areas as $spend_area )
            {
                $geo_point = new GeoPoint();
                $geo_point->setLatitudeInMicroDegrees( $spend_area[ 'latitude' ] * 1000000 );
                $geo_point->setLongitudeInMicroDegrees( $spend_area[ 'longitude' ] * 1000000 );
                $proximity = new Proximity();
                $proximity->setRadiusInUnits( $spend_area[ 'radius' ] );
                $proximity->setRadiusDistanceUnits( ProximityDistanceUnits::MILES );
                $proximity->setGeoPoint( $geo_point );
                $proximities[] = new CampaignCriterion( $campaign_id, null, $proximity );
            }
            return $proximities;
        }
`

$spend_area[ 'radius' ] comes from a mysql INT column via Laravel's ORM massaged into an array via this line:

` $custom_locations[] = array( 'latitude' => $spend_area->latitude, 'longitude' => $spend_area->longitude, 'radius' => $spend_area->radius );
`

... in the above, $spend_area is a Laravel 5.2 Eloquent model object. 

-Thom

**Comment by fiboknacky** [comment]
Hi Thom,

`radiusInUnits` should be a double (float) value.
Do you have a sample of what `$spend_area['radius']` could be?
I still wonder why it appears as `00:00:50Z`.

Best,
Knack

**Comment by thomhickey** [comment]
We're sending values like 50, 20, 10, 30. Incidentally we upgraded to PHP7 in our prod env this morning and the problem went away so it's definitely something with PHP 5.6.

**Comment by thomhickey** [comment]
Looks like upgrading to php 7 did resolve the issue in our prod env, fyi.

**Comment by fiboknacky** [comment]
Hi Thom,

I would need full SOAP logs for the operations you've sent to the server using PHP 5.6.
Most of the Unmarshalling Error reported so far is due to misuse of the constructors or setters, hence resulting in the SOAP XML requests that are wrong.
But from your code snippet, it looks fine to me.

One last question, you've said:
> in the logs and the mutation is successful. Really scratching our heads with this one. Also, if we force '00:00:50Z' into the radius value at runtime,

I wonder why you were trying to do so?
'00:00:50Z' is obviously not of correct data type (`xsd:double`).
Would you like to try if it really fails?

As a side note, it looks like a different issue from what's originally reported in this issue.
Thanks very much so far anyway.

Cheers,
Knack

**Comment by thomhickey** [comment]
Hi Knack ... yes, I wanted to see if we could reproduce the unmarshalling error by sending in wrong data. We knew it was wrongly typed, just thought it might shed some light. No need to investigate that, thanks.

I can send you the logs, but would prefer to send privately for security reasons, is that ok?

**Comment by fiboknacky** [comment]
Hi Thom,

Thanks so much for your help!
Please send the log to adwordsapiadvisor@google.com and mention this GitHub issue number and my name.

Thanks in advance.
Knack

**Comment by thomhickey** [comment]
Ok, email is sent with the api log attached.

**Comment by fiboknacky** [comment]
Hi Thom,

Sorry for the late reply.
I've tried sending invalid requests to the servers using different PHP versions and found that it would be just the differences of how PHP SoapClient handles this case of errors.
In my case, PHP 5.6.x returns ApiException but PHP 5.5.x returns unmarshalling errors.

In either case, SoapClient does its job well to catch and throw this error already, so this works as intended.

Best,
Knack

**Comment by thomhickey** [comment]
Thanks, Knack. Not sure why you were sending invalid requests, that was never the problem. It was only something I was trying during debugging. The problem I reported originally was that the same request would fail in 5.6 and succeed in PHP 7 so it obviously was not an invalid request.

**Comment by fiboknacky** [comment]
Sorry if that was not clear. I couldn't reproduce the issue when passing the invalid request as well.

**Comment by fiboknacky** [comment]
Nope. Everything looks correct.

**Comment by thomhickey** [comment]
Ok thanks for looking into it, Knack. Take care.
