### ISSUE TITLE
run example [RunInventoryReport], get error

### ISSUE THREAD

**Issue by Mavis00** [googleads/googleads-php-lib#286]
Hi, 

I need to get revenue report data from API.

I can get the result from example \examples\Dfp\v201702\OrderService\GetOrdersStartingSoon.php successfully. But I got error from the example \examples\Dfp\v201702\ReportService\RunInventoryReport.php, it show error msg as the following:

`PHP Catchable fatal error:  Argument 1 passed to GuzzleHttp\Psr7\rewind_body() must implement interface Psr\Http\Message\MessageInterface, null given, called in C:\inetpub\wwwroot\dfp_api\src\Google\AdsApi\Common\GuzzleLogMessageHandler.php on line 74 and defined in C:\inetpub\wwwroot\dfp_api\vendor\guzzlehttp\psr7\src\functions.php on line 274`

- myOS is windows 7
- the file I ran from browser is http://192.168.200.129/dfp_api/test-RunDeliveryReportForOrder.php, this page is copied from \examples\Dfp\v201702\ReportService\RunInventoryReport.php, and what I only did is changed vender path to "require 'vendor/autoload.php';"

Would you please help me out?

Thanks a lot.

**Comment by fiboknacky** [comment]
Hi @Mavis00 

Sure. We're here to help. :-)

First, could you please confirm the client library version you're using?
Do you use the latest version or a bit earlier version?

The underlying issue would be related to the timeout value. More details can be found in #246.
To fix this, could you please try what's described in [this section](https://github.com/googleads/googleads-php-lib#reporting) by setting larger value of timeout?
When the default timeout is too small, the result will not be packed as `Response` properly and thus `null` is assigned to `$response` in [this line](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/GuzzleLogMessageHandler.php#L62). 

When `$response` is passed to the function in [line 74](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/GuzzleLogMessageHandler.php#L74), it thus fails.
We're also fixing this so that `null` will not be passed to `rewind_body()` anymore.

Best,
Knack

**Comment by fiboknacky** [comment]
I close this issue due to inactivity.
In addition, recently we've refactored [`GuzzleLogMessageHandler`](https://github.com/googleads/googleads-php-lib/blob/27.1.0/src/Google/AdsApi/Common/GuzzleLogMessageHandler.php) since [v27.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/27.0.0).
Please update to the [latest version](https://github.com/googleads/googleads-php-lib/releases/tag/27.1.0) and try again.

Best,
Knack
