### ISSUE TITLE
Multiple requests in one call

### ISSUE THREAD

**Issue by yooouuri** [googleads/googleads-php-lib#293]
When i use the ```BatchJobService``` to send requests, does it count for only one API call or does the ```BatchJobService``` send the requests individually (like normal)?

If not, is there an other solution? Because i need to send like 80.000 campaigns, groups, ads etc per day in some situations...

Is there a way to get my amount of api calls this day?

Maybe this is not the right place to ask...

Youri

**Comment by fiboknacky** [comment]
Hello Youri,

No worries! Please feel free to ask.

As for your question, the short answer is no, operations aren't counted separately.
In fact, `BatchJobService` and batch processing are created for helping developers submit their requests, which might be composed of a large number of operations, and also may take long time to complete, in an async fashion.
That's why even if you send operations to create 80,000 campaigns, they aren't counted separately.

Note that, however, the servers are shared resources so you may still be subjected to rate limiting, if you send too many requests.
Please see our guide about [rate limits](https://developers.google.com/adwords/api/docs/guides/rate-limits) for more detail.

By the way, in the future, for the AdWords API general questions, you can ask in [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api), which is monitored by many people in our team.
For the PHP client library specific questions, this is the exactly right place to ask. :-)

Best,
Knack

**Comment by fiboknacky** [comment]
Hi Youri,

It looks like I misunderstood your questions. Sorry for this.
Let me explain the operation counts limits more.

The benefits of using BatchJobService I described above is rather about avoiding [rate limits](https://developers.google.com/adwords/api/docs/guides/rate-limits#types_of_rate_limits) due to too much _operations per minute_ or _requests per minute_. 
This is because BatchJobService schedules your requested operations properly and also recover from transient errors.

However, if your [AdWords API access level](https://developers.google.com/adwords/api/docs/ratesheet#adwords-api-access-levels) is **basic**, your developer tokens are still subjected to the limit that allows up to 10,000 operations per day.
_Those that are sent via BatchJobService are also counted towards this limit._
Should you need more operations per day, please consider apply for **standard access** via [this page](https://www.google.com/appserve/fb/forms/standardaccess/).

I'll close this issue as it's not related directly to this client library.
Feel free to contact us in [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api) if you need more help about this.

Sorry for the misleading information again.

Best,
Knack
