### ISSUE TITLE
ReportSettingsBuilder -> AdsBuilder: fromFile method missing

### ISSUE THREAD

**Issue by cephuo** [googleads/googleads-php-lib#328]
In the latest release (28.0) the `fromFile` method was removed which used to load the configuration .ini file and apply the settings (`[ADWORDS_REPORTING]`) to the report builder.

Version 26.0:
```
$reportSettings = (new ReportSettingsBuilder())
	->fromFile($configFilePath)
	->build();
```

Version 28.0 (with workaround):
```
$configuration = (new ConfigurationLoader())->fromFile($configFilePath);
$reportSettings = (new ReportSettingsBuilder())
     ->from($configuration)
     ->includeZeroImpressions($includeZeroImpressions)
     ->build();
```

**Comment by fiboknacky** [comment]
Hello @cephuo,

Sorry for confusion that might occur to you.
In fact, if you put the settings in `[ADWORDS_REPORTING]` of the `adsapi_php.ini`, it will be read automatically, when you call `build()` of `AdWordsSessionBuilder` (see [this line](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php#L127)).
That's why we removed that `fromFile()` from `ReportSettingsBuilder`.

To conclude, you can still add reporting settings in the `adsapi_php.ini` as before. 
They will be read automatically.
What we improved in v28.0.0 is that now you can inject ad-hoc report settings for each report download, without creating new session and report settings objects every time (see [this example](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201705/Reporting/DownloadCriteriaReportWithAwql.php#L44)).

Let me know if you have further questions.

Best,
Knack

**Comment by cephuo** [comment]
Hello @fiboknacky,
Thank you for the fast reply.

As it looks, the reportsSettings will be taken from the $session only when there is no $reportSettingsOverride passed to the downloadReport* methods.

At the end $reportSettingsOverride is passed to this method:
```
RequestOptionsFactory => createHeaders(ReportSettings $reportSettingsOverride = null) {
....
    $reportSettings = $reportSettingsOverride;
    if (is_null($reportSettings)) {
      $reportSettings = $this->session->getReportSettings();
    }
....
}
```

So the injected ad-hoc report settings will not be merged with the ones coming from the $session, but will overwrite them.

**Comment by fiboknacky** [comment]
Hello,

The constructor of `ReportSettingsBuilder` accepts `ReportSettings` as a parameter (see [this line](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/ReportSettingsBuilder.php#L46)).
So, you can pass the old report settings regardless of whether it's `$this->session->getReportSettings()` or any other previous settings objects, to the constructor.

Then, you can just set the options (e.g., [includeZeroImpressions()](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/ReportSettingsBuilder.php?utf8=%E2%9C%93#L144)) you want by retaining the existing options, before calling `build()`.

Best,
Knack
