### ISSUE TITLE
Page showing blank..

### ISSUE THREAD

**Issue by oeanwaar** [googleads/googleads-php-lib#347]
Hi there,
I am using adwords API on my local machine on XAMPP. I installed PHP Clinet API through Composer, every thing is working fine i can fetch data, can run any report i want. But now i want to upload this project on  live server. I uploaded all files on my server, but when i run it shows blank page. i have some questions
1. I need to run composer online again
2. If no then how my auto loader will work then.

**Comment by fiboknacky** [comment]
Hello @oeanwaar 

From my experience, blank page can occur due to many reasons, ranging from that the output is not printed properly (note that our examples are meant to run in command line) to that a server prevents SOAP calls or doesn't have necessary components installed.
If you have uploaded all files including those in the `vendor/` directory, it should be fine to use the library on the server as is.

Could you tell me more what code you've run? Any of our example files?
Could you turn on error reporting of PHP and try again too?

Best,
Knack

**Comment by oeanwaar** [comment]
yes i have uploaded all files. 
Please can you mention. how i can send you my code files?

**Comment by fiboknacky** [comment]
If not so long, could you just paste it here?

**Comment by oeanwaar** [comment]
before i send you code. One issue
when i run v201708/BasicOperations/GetCampaigns.php on my local machine. it shows all campaigns. but i run same file on Live server its show 500 Error. Image attached. 
![capture](https://user-images.githubusercontent.com/31469328/29866189-922cc07c-8d6f-11e7-8e92-928b91868541.PNG)

**Comment by fiboknacky** [comment]
Does your server have PHP, SoapClient, and SSL installed and doesn't have any settings / proxies that prevent the lib from making SOAP calls?

Knack

**Comment by oeanwaar** [comment]
i comment all code and only run aoutload.php file 
Parse error: syntax error, unexpected '[' in /httpdocs/email/report/costapi/google/vendor/guzzlehttp/psr7/src/functions.php on line 78

i need to set path when i upload all files to live server?

**Comment by fiboknacky** [comment]
Can you share your code please?
What portion did you comment out?
What did you mean by running only `autoload.php` file? Do you mean the part at the beginning of our example files?

The error message looks strange to me. It looks like your copied files are not complete as there shouldn't be syntax errors in the files of Guzzle lib itself.

I recommend to do `composer install` on your live server instead of copy-and-paste though.

Knack
