### ISSUE TITLE
Invalid Adgroup ID returned in GetAdGroups.php

### ISSUE THREAD

**Issue by ztobs** [googleads/googleads-php-lib#359]
When trying to run GetAdGroups.php in BasicOperation example.
I got the collection of Adgroups in that campaign, the Adgroup Names were correct but the Adgroup Ids were not. It also includes negative vales which obviously an id cannot be negative.

**Comment by fiboknacky** [comment]
Hello,

I guess your PHP is 32-bit, that's why `%d` in [this line](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201708/BasicOperations/GetAdGroups.php#L65) is sometimes shown as negative numbers.

Try changing `%d` in [this line](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201708/BasicOperations/GetAdGroups.php#L65) to `%s`.

Best,
Knack

**Comment by ztobs** [comment]
I didnt use exactly the lines of code. I changed
`printf(
              "Ad group with ID %d and name '%s' was found.\n",
              $adGroup->getId(),
              $adGroup->getName()
          );`

to
`$results[] = array($adGroup->getId() => $adGroup->getName());`

Then printed the array when all was done
So, i guess that wasnt the cause.

Did you try it and got accurate ids?

**Comment by fiboknacky** [comment]
If I'm correct, your code still prints negative numbers if your PHP is 32 bit. 
To confirm this, could you try printing out `PHP_INT_SIZE`?
And can you try `$results[] = array(strval($adGroup->getId()) => $adGroup->getName());`?

> Did you try it and got accurate ids?
Yes, I got correct IDs.

Best,
Knack

**Comment by ztobs** [comment]
PHP_INT_SIZE prints 4
Can i increase it?

**Comment by fiboknacky** [comment]
That means your PHP is 32-bit. It's not something that you can change because it depends on your installed PHP.
As mentioned in [this section](https://github.com/googleads/googleads-php-lib#basic-usage), you would need to adjust the code accordingly. 
The first action to do is not to use `intval()`. Passing the value directly as an index to an array also results in negative numbers in 32-bit PHP too.

**Comment by ztobs** [comment]
Thanks, i think that's enough information.
What if floatval was used, would my code still be able to run on 64bit machine? Because its going to be deployed on 64bit machine.

**Comment by fiboknacky** [comment]
Yes, it should affect only when you're trying to print out information on your machines.
Data sent to the servers should be fine.
