### ISSUE TITLE
class AdParamPage should extend \Google\AdsApi\AdWords\v201702\cm\Page

### ISSUE THREAD

**Issue by davido-brainlabs** [googleads/googleads-php-lib#380]
The class AdParamPage should extend \Google\AdsApi\AdWords\v201702\cm\Page but doesn't.

**Comment by fiboknacky** [comment]
Hello @davido-brainlabs 

The class is generated from WSDL file (which is also generated as a [reference page](https://developers.google.com/adwords/api/docs/reference/v201708/AdParamService.AdParamPage)).
As you can see, the AdParamPage class doesn't extend from Page. That's why it's not generated as a child class in this library as well.

Best,
Knack

**Comment by fiboknacky** [comment]
As the answer is given, I'll close this issue.
