### ISSUE TITLE
Features which are not present in the library

### ISSUE THREAD

**Issue by seanlokeee** [googleads/googleads-php-lib#430]
Hi,

A newbie in API programming. Out from the google api developers documentation, what features are not present in the current Examples folder? (https://developers.google.com/adwords/api/docs/guides/budget-order). E.g. I do not see Budget Order Service.  

Q1. I am learning how to build an API. To guide me to build an API, could you point me to the features which are not present so that I can experiment with it.
Q2. What steps would you advice me to take after completing the getting started which took me 2-3days to bug fix the adapsi.ini?

Thank you.

**Comment by fiboknacky** [comment]
Hello @seanlokeee 

Currently, we have only Java examples for Budget Order Service, but the class organizations between our Java library and this PHP library are very similar, so you could mimic them with not too much effort.
Could you please try first and let us know which part is not clear to you?

> Q1. I am learning how to build an API. To guide me to build an API, could you point me to the features which are not present so that I can experiment with it.

I'm not quite sure why you would like us to point to the features that are not present? Could you please explain a bit more?
Instead of that, could you tell us what you'd like to do so I can help more straightforwardly?

> Q2. What steps would you advice me to take after completing the getting started which took me 2-3days to bug fix the adapsi.ini?

I'm afraid I don't understand your question clearly. It looks like you've faced with some problems during the client library setup? If so, could you elaborate? In what steps you got stuck and what errors did you get?

Thanks,
Knack

**Comment by seanlokeee** [comment]
Hi knack,

Thanks for your quick response. I want to implement additional features to the examples but I'm not quite sure what features has been already implemented and features which have not. 

There are no errors, everything is working. I just want a brief advice on what steps I should proceed after the getting started process as I am a newbie (e.g. Where can I learn to implement my own features other than the google documentation)

**Comment by fiboknacky** [comment]
Hello @seanlokeee 

Sorry for late response. I'm just back from holidays.

> I just want a brief advice on what steps I should proceed after the getting started process as I am a newbie (e.g. Where can I learn to implement my own features other than the google documentation)

I assume your "features" here mean a new utility class or new methods in existing utilities.
(Please correct me if I'm wrong)

If so, you'd want to go through the codes in [`src/Google/AdsApi/`](https://github.com/googleads/googleads-php-lib/tree/master/src/Google/AdsApi) to see how the classes are organized. You then can follow any best practice for software development to implement the relevant parts.
Some conventions and underlying designs are summarized in [this guide](https://github.com/googleads/googleads-php-lib/blob/master/UPGRADING.md).

As for coding style, we don't have published guidelines yet but you could refer to our existing codes.
You're very welcome to submit a [pull request](https://github.com/googleads/googleads-php-lib/pulls) if you wish to contribute to this library.

Best,
Knack

**Comment by fiboknacky** [comment]
Close due to inactivity.
