### ISSUE TITLE
Old library support

### ISSUE THREAD

**Issue by spatariu** [googleads/googleads-php-lib#469]
Do you think we can get a library with the old (deprecated) workflow (current version 19 in releases)? It would be a great help since v201705 is ending next week and we have little time to update. At least for v201710 would be great, thanks!

**Comment by fiboknacky** [comment]
Hello @spatariu 

Unfortunately, the old library has reached the end of life.
We already announced this in #193 since the end of 2016.
Please migrate to the new version as soon as possible.
The [upgrading](https://github.com/googleads/googleads-php-lib/blob/master/UPGRADING.md) guide is here.

Best,
Knack

**Comment by spatariu** [comment]
I know.. but you kept adding support until v19 of the release.. tx anyway!

**Comment by fiboknacky** [comment]
That was planned as stated in #193. We supported up to July, 2017, which is until v19.
