### ISSUE TITLE
Uncaught SoapFault exception: [HTTP] Could not connect to host in

### ISSUE THREAD

**Issue by DevMoust** [googleads/googleads-php-lib#480]
i'm trying to connect in adwords with the googleads-php-lib but still ocurring this error 

( ! ) Fatal error: Uncaught SoapFault exception: [HTTP] Could not connect to host in C:\wamp64\www\semwp\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php on line 97
--

1 | 0.0010 | 387808 | {main}( ) | ...\index.php:0
2 | 0.0490 | 2332672 | Google\AdsApi\AdWords\v201802\cm\CampaignService->get( ) | ...\index.php:43
3 | 0.0490 | 2333456 | Google\AdsApi\Common\AdsSoapClient->__soapCall( ) | ...\CampaignService.php:163

can someone help me?

**Comment by DevMoust** [comment]
I already did this steps and still having problems :s
![error](https://user-images.githubusercontent.com/38473032/38889539-69172f92-4255-11e8-8099-e759e5a1576f.jpg)

**Comment by fiboknacky** [comment]
Where is your SSL CA file and you did all three steps?
Does this happen every time or sometimes?

**Comment by DevMoust** [comment]
I did the process again and it worked, Thank You :D

**Comment by fiboknacky** [comment]
Glad you can resolve the issue. :-P

**Comment by kakugiki** [comment]
I had the same issue but only when I try to run it as a web app instead of from a console. I already have set curl.cainfo in php.ini, which give me no problem to run it from Windows command line. But I have to set openssl.cafile pointing to the same crt file in order to run it as a web site. So it's not "Explicitly set openssl.cafile OR curl.cainfo in your php.ini to the path of your CA file. " but should be written as "Explicitly set openssl.cafile AND curl.cainfo in your php.ini to the path of your CA file. "?!

**Comment by fiboknacky** [comment]
Thanks. I've updated the instructions.
