### ISSUE TITLE
Convenient functions in MediaUtils

### ISSUE THREAD

**Issue by woodstocktm** [googleads/googleads-php-lib#484]
While upgrading to new client library, I noticed that MediaUtils passed away - perhaps this should be commented in Upgrading-Guide to prevent bugs and users from searching too long ;-)

**Comment by fiboknacky** [comment]
Hello,

Sorry that this caused you some inconvenience and thanks for the feedback.
Basically, we didn't want users to blindly upgrade the library, but rather we wish users to go through our code examples again to see how to do things in the new library.

I think you've already figured out what can be used instead of MediaUtils, so I'm going to close this issue, but please let me know, if you need further help.

Again, thank you for your feedback. :)

Knack
