### ISSUE TITLE
Strange service accounts warnings

### ISSUE THREAD

**Issue by marcinrosinski** [googleads/googleads-php-lib#510]
Hi there,

we have updated to the latest SDK version and are now getting the following error which kinda makes no sense as service accounts have no access to adwords campaigns so not sure what is this about, see below:

    Warning: Your application has authenticated using end user credentials from Gooogle Cloud SDK. 
    We recommend that most server applications use service accounts instead. If your application 
    continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or 
    "API not enabled" error.
    
    For more information about service accounts, see https://cloud.google.com/docs/authentication/. in /myproject/vendor/google/auth/src/Credentials/UserRefreshCredentials.php on line 92

any ideas?

**Comment by fiboknacky** [comment]
Hello there,

It's due to an issue of [google/auth](https://github.com/google/google-auth-library-php) v1.3.1.
If you update it to [v1.3.2](https://github.com/google/google-auth-library-php/releases/tag/v1.3.2) (by, e.g., removing it from the `vendor` folder and running `composer update` again), this should go away.

Best,
Knack

**Comment by fiboknacky** [comment]
Closed as the solution has been offered.
