### ISSUE TITLE
Adwords API : GetCampaign.php > Number of results found: 0

### ISSUE THREAD

**Issue by ico7liv** [googleads/googleads-php-lib#534]
Hello,

I have a problem using the Adwords API.
I validated my Adwords API Developer Token, in my Manager account.

Then I wanted to test the API with a client TEST account.
I need your help because when I run GetCampaign.php, there are no campaigns found.
 
Here is our setup :
 
Production Adwords Manager Account : boris.betc@gmail.com
API Developer token : the token I get after the validation process (I can give it to you in private)
Access level : basic access validated
 
 
TEST account : betctestmanagerads@gmail.com
ID Manager TEST: 524-293-1082
ID Client TEST: 368-235-5970
 
Setup file used > adsapi_php.ini (I can give it to you in private)
 
Google Cloud Platform Application ID, used for refreshToken : test-adwords-218209
 
Result GetCampaigns.php : Number of results found : 0
Console Screenshot > https://imgur.com/a/fJHTjnt

Thanks for your help :)

**Comment by fiboknacky** [comment]
Hello,

It looks like you've created a video campaign.
The AdWords API doesn't support video campaigns via SOAP services, as mentioned in [this page](https://developers.google.com/adwords/api/docs/reference/v201809/CampaignService).
That's why you cannot retrieve any campaigns back.

You can still fetch info about video campaigns using [VIDEO_PERFORMANCE_REPORT](https://developers.google.com/adwords/api/docs/appendix/reports/video-performance-report).

Best,
Knack
