### ISSUE TITLE
makeTestNetwork Not Working

### ISSUE THREAD

**Issue by GLStephen** [googleads/googleads-php-lib#557]
Calls to MakeTestNetwork are not working. Issues:

1. The makeTestNetwork call is returning saying that networkCode is required on the session, it's not supposed to be for calls to makeTestNetwork according to here:

https://developers.google.com/ad-manager/api/soap_xml

2. Providing proper info and a networkcode (from another account) to get past this point results in:

```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://www.google.com/apis/ads/publisher/v201811"><SOAP-ENV:Header><ns1:RequestHeader><ns1:networkCode>REAL_CODE_BUT_NOT_THIS_CODE</ns1:networkCode><ns1:applicationName>SJ Test Network 2 (DfpApi-PHP, googleads-php-lib/38.0.0, PHP/7.1.23)</ns1:applicationName></ns1:RequestHeader></SOAP-ENV:Header><SOAP-ENV:Body><ns1:makeTestNetwork/></SOAP-ENV:Body></SOAP-ENV:Envelope>
```
Results in:

```
HTTP/1.1 500 Internal Server Error
Content-Type: text/xml; charset=UTF-8
Date: Fri, 04 Jan 2019 16:12:06 GMT
Expires: Fri, 04 Jan 2019 16:12:06 GMT
Cache-Control: private, max-age=0
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Alt-Svc: quic=":443"; ma=2592000; v="44,43,39,35"
Accept-Ranges: none
Vary: Accept-Encoding
Connection: close

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Header><ResponseHeader xmlns="https://www.google.com/apis/ads/publisher/v201811"><requestId>3f04f67118a40f2751c9707ab9edf657</requestId><responseTime>283</responseTime></ResponseHeader></soap:Header><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>[ServerError.SERVER_ERROR @ ]</faultstring><detail><ApiExceptionFault xmlns="https://www.google.com/apis/ads/publisher/v201811"><message>[ServerError.SERVER_ERROR @ ]</message><errors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ServerError"><fieldPath></fieldPath><trigger></trigger><errorString>ServerError.SERVER_ERROR</errorString><reason>SERVER_ERROR</reason></errors></ApiExceptionFault></detail></soap:Fault></soap:Body></soap:Envelope>
```

**Comment by thangduo** [comment]
Hi Stephen,

Sorry, I don't understand your questions.

Regarding the issue #1, the `makeTestNetwork()` function doesn't require any parameters. Please see the MakeTestNetwork example [line 65](https://github.com/googleads/googleads-php-lib/blob/1f3024348586af6e0ac4630e18fa71473c1f9465/examples/AdManager/v201811/NetworkService/MakeTestNetwork.php#L65).

Please note that the test network must be created and associated with a production network. You must authenticate to a production network in the adsapi_php.ini file ([line 4](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdManager/adsapi_php.ini#L4)) in order to execute the `makeTestNetwork()` function.

![networkcode](https://user-images.githubusercontent.com/4349155/50742867-7d0e1e80-11de-11e9-8fa4-2278dd5bb284.png)

Regarding issue #2, it is a permission issue. Please refer to the Test vs. Production [guide](https://developers.google.com/ad-manager/api/environments) for more details.

![note](https://user-images.githubusercontent.com/4349155/50742880-adee5380-11de-11e9-97b2-926b0172458e.png)

**Comment by GLStephen** [comment]
A test network does not (is not supposed to) require a production network. Which is mentioned in multiple places including the v28011 sample code you reference above in the comments:

```
This example creates a test network. You do not need to have an Ad Manager
 * account to run this example, but you do need to have a Google account
 * (created at https://www.google.com/accounts/newaccount if you currently don't
 * have one) that is not associated with any other Ad Manager test networks.
 * Once this network is created, you can supply the network code in your
 * ads.properties file to make calls to other services.
```
I'm not talking about makeTestNetwork requiring parameters. I'm talking about bot being able to send requests to make a test network without sending a network code.

I've made test networks in the past without a related production network.

If this is a new requirement, how would I possibly have multiple test networks for different apps or clients, while having the underlying AdSense requirements met.

Something doesn't make sense here.

**Comment by thangduo** [comment]
Hi Stephen,

Thanks for reporting this issue to us. You are correct that you should be able to create a test network with a new Google account (a Gmail account, for example) without having to tie it to any Google Ad Manager production networks.

The error that you are getting could be caused by a recent change. We are checking this issue on our end. And, I will update this thread when we have more info.

Thanks,
Thang Duong

**Comment by fiboknacky** [comment]
Closing due to no more activities.
