### ISSUE TITLE
New Google Ads API by 30th of April 2019

### ISSUE THREAD

**Issue by hybmg57** [googleads/googleads-php-lib#573]
According to [this](https://ads-developers.googleblog.com/2019/03/upgrade-to-new-google-ads-api-to-get.html) news looks like Google Ads API is going away by April 30 2019. Does it mean this library is no longer use after this update?

**Comment by fiboknacky** [comment]
Hello,

The Google Ads API is NOT going away. 
What's going away is v0 (Beta) of the [Google Ads API](https://developers.google.com/google-ads/api/docs/start), meaning that the Google Ads API is out of Beta and is now **production-ready**.
So, if you're using our [new client library for PHP](https://github.com/googleads/google-ads-php), you can update to our latest version that support v1 soon. (We are working on that)

Note also that the Google Ads API is the new API and the [AdWords API](https://developers.google.com/adwords/api/docs/guides/start) is the old one.
This library is for **the old AdWords API**.

Because the AdWords API's [last version is v201809](https://developers.google.com/adwords/api/docs/sunset-dates), so yes, it's correct that we're not updating any new versions for the AdWords API in this library anymore.
Once the AdWords API v201809 is sunset (the date is not fixed yet), this library will be totally for the Google Ad Manager API.

Best,
Knack
