### ISSUE TITLE
effect of Adwords API v201809 sunset 

### ISSUE THREAD

**Issue by hybmg57** [googleads/googleads-php-lib#574]
thanks for the prompt response! Does it mean after Adwords API v201809 sunset there won't be any new version anymore on this library and I would have to start using [new client library for PHP](https://github.com/googleads/google-ads-php) and is the migration to this new library require much effort?

**Comment by fiboknacky** [comment]
> thanks for the prompt response! Does it mean after Adwords API v201809 sunset there won't be any new version anymore on this library 

If you mean new version of *AdWords API*, correct.
There will be no new versions anymore.
Actually, there have been no new versions since September, 2018.

> and I would have to start using new client library for PHP and is the migration to this new library require much effort?

Yes, you should start using it right now and plan for migration very soon.
Whether it requires much effort or not quite depends on your application as well, so I cannot guarantee that it will be easy or hard.
But many of the concepts are borrowed from the AdWords API, e.g., campaigns, ad groups, ads.
So, you can expect to see similar concepts around the library.

Knack

**Comment by chiragvels** [comment]
Hello @fiboknacky ,
Reporting are not similar any more, even I found difficulty to match some of the reports.
Like Placeholder Feed Item Report or some of the Criteria Related reports.
I don't see any view for this. Also there is some resources like customer object is difficult to match.

Can you please also clear that the refresh token that were automatically updates(When we callAdwordsUser Service) itself is still same on new Ads API as well?



Thanks,

**Comment by fiboknacky** [comment]
For migration, we've provided this [extensive guide](https://developers.google.com/google-ads/api/docs/migration/overview). Please find time to read through it.
If you have any questions, feel free to reach out to the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api).

> Can you please also clear that the refresh token that were automatically updates(When we callAdwordsUser Service) itself is still same on new Ads API as well?

The authentication approach is still the same: You need a developer token and OAuth2 credentials.
I recommend going through [this Quickstart guide](https://developers.google.com/google-ads/api/docs/first-call/overview) and [this OAuth2 doc](https://developers.google.com/google-ads/api/docs/oauth/overview) for more details.

Best,
Knack
