### ISSUE TITLE
How to create campaign in laravel ?

### ISSUE THREAD

**Issue by harshit1235** [googleads/googleads-php-lib#576]
HI,

I download laravelsample code using git clone.

I want sample code  for create campaign in laravel.

I tried since last few days but not found way in laravel.

Please help me.

Thanks&Regards

**Comment by fiboknacky** [comment]
Hello,

We don't have an example of creating campaigns in Laravel, partly due to the fact that everyone would have his/her own way of creating a UI for that.
Our goal to provide LaravelSampleApp is to show how to integrate the library with MVC frameworks.
So, we picked up an example of getting campaigns because of its simplicity of showing results.

But you should be able to adapt from [this code example](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201809/BasicOperations/AddCampaigns.php) easily.
What you'd need to do is to add more actions in the controller part, like [getCampaignsAction()](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/LaravelSampleApp/app/Http/Controllers/AdWordsApiController.php#L67).

You should be able to use AdWordsSessionBuilder and AdWordsServices(), in a similar way as that method.

Best,
Knack

**Comment by harshit1235** [comment]
Thanks for give link as a reference purpose
