### ISSUE TITLE
Error: OperationAccessDenied : ADD_OPERATION_NOT_PERMITTED In laravel

### ISSUE THREAD

**Issue by harshit1235** [googleads/googleads-php-lib#577]
Hi,

I am facing issue when creating campaign.

click on link for show Issue Screenshot:

https://user-images.githubusercontent.com/48353622/54039086-0b574e80-41e8-11e9-8a19-4653dddd4c52.png

Please help me for solving this issue.

Thanks&Regards

**Comment by fiboknacky** [comment]
[ADD_OPERATION_NOT_PERMITTED](https://developers.google.com/adwords/api/docs/common-errors#OperationAccessDenied.ADD_OPERATION_NOT_PERMITTED) can be because of you're sending request to the manager account, not the client account.

For further questions regarding this, could you ask in [AdWords API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead, as this is not client library-issue?
Feel free to open new issues here if they're related to this client library.

Best,
Knack
