### ISSUE TITLE
BatchJobDelegate v201809 using deprecated Symfony version

### ISSUE THREAD

**Issue by andjelboskovic** [googleads/googleads-php-lib#590]
Hello,

I'm using function BatchJobs to upload Ad Customizer Feed updates and I'me receiving the following error in my server log:

2019-05-21 08:10:27 --> Severity: 16384  --> Passing configuration options directly to the constructor is deprecated since Symfony 4.2, use the default context instead. /var/www/prod/vendor/symfony/serializer/Encoder/XmlEncoder.php 80

I've managed to trace the error back to

File: v201809/BatchJobsDelegate

121  $this->batchJobSerializer = new Serializer(
122     [$adWordsNormalizer, new ArrayDenormalizer()],
123     [new XmlEncoder('ns1:mutate')]
124 );

Line 123 ^^^

Since the version of Symfony is dependent on the one defined in composer.json how do you suggest I approach solving the issue?

Thanks in advance,
Andjel

**Comment by fiboknacky** [comment]
Hello Andjel,

I have no time to investigate this in detail yet, but if the syntax of passing configuration options to the constructor is deprecated, Symfony would probably provide other options to that instead.
Is it possible for you to hard-code the new style in the BatchJobsDelegate file instead?

It's very less likely that we'll change that file from now, because the AdWords API is already deprecated, so it'd be safe for now to hard-code the change.
In the long term, we're providing the batch job-like feature in the [Google Ads API](https://developers.google.com/google-ads/api/docs/start), so you can migrate over to it.

Best,
Knack

**Comment by andjelboskovic** [comment]
Hey Knack,

Thank you for your answer.

Best regards,
Andjel

*Andjel Boskovic *| Marketing
*FishingBooker.com*
Book Fishing Charters Worldwide

W: fishingbooker.com
@: andjel.boskovic@fishingbooker.com
*facebook <http://www.facebook.com/Fishingbooker> | twitter
<http://twitter.com/FishingBooker> | linkedin
<https://www.linkedin.com/company/fishingbooker>** |* *google+
<http://google.com/+Fishingbookercom/>*

Confidentiality Notice: This email may contain confidential and/or private
information. If you received this email in error please delete and notify
the sender.

**Comment by fiboknacky** [comment]
Sure. Please let me know if you need any help.
