### ISSUE TITLE
LibraryMetadataProvider might trigger a warning, continue

### ISSUE THREAD

**Issue by adriansuter** [googleads/googleads-php-lib#595]
I could not post a reply to #594. GitHub said, that I can't do that this time. So here it is in a new issue (sorry for that):

> Could you elaborate more how it's disabled and what kind of message you see?

@fiboknacky Sure.

The function is set in the disabled functions in `php.ini` (see https://www.php.net/manual/en/ini.core.php#ini.disable-functions).

The message is
```
Warning: parse_ini_file() has been disabled for security reasons in Google\AdsApi\Common\LibraryMetadataProvider->__construct() (Line 31 in /www/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/LibraryMetadataProvider.php).
```

Of course, I could convince my hosting provider to remove that function from the list of disabled functions - indeed I already started that process. But then this might be still an issue for other users.

**Comment by fiboknacky** [comment]
Thanks for more information.
Looks like any internal functions can be defined as a disabled function in the `php.ini` file.
As each user has his/own purpose and ways of using PHP in each environment, so I'm afraid even if we somehow do something with this parse_ini_file() (such as using other functions to do the job instead), it wouldn't guarantee there wouldn't be similar problems in the future (such as host provider banned other functions instead of this one).

**Comment by adriansuter** [comment]
Agree.
