### ISSUE TITLE
ads api send invitations to other managed accounts or just receive?

### ISSUE THREAD

**Issue by Claudio2424** [googleads/googleads-php-lib#600]

**Comment by fiboknacky** [comment]
I don't get what you asked. Could you please include more details?

**Comment by Claudio2424** [comment]
I would like to make this call in php

ex: 

LinkOperation linkOp = new LinkOperation();
ManagedCustomerLink link = new ManagedCustomerLink();
link.setClientCustomerId(CLIENT_CID);
link.setLinkStatus(LinkStatus.PENDING);
link.setManagerCustomerId(MANAGER_CID);
linkOp.setOperand(link);
linkOp.setOperator(Operator.ADD);
managedCustomerService.mutateLink(new LinkOperation[]{linkOp});

**Comment by Claudio2424** [comment]
this code in php returns the error

Fatal error: Uncaught Google\AdsApi\AdWords\v201809\cm\ApiException: [ManagedCustomerServiceError.NOT_AUTHORIZED @ operations[0]] in /var/www/html/trabalho/googleAds/Api/src/libs/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php:43 Stack trace: #0 /var/www/html/trabalho/googleAds/Api/src/libs/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php(43): ReflectionClass->newInstanceArgs(Array) #1 /var/www/html/trabalho/googleAds/Api/src/libs/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(202): Google\AdsApi\Common\Util\Reflection->createInstance('Google\\AdsApi\\A...', Array) #2 /var/www/html/trabalho/googleAds/Api/src/libs/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(164): Google\AdsApi\Common\AdsSoapClient->parseApiExceptionFromSoapFault(Object(SoapFault)) #3 /var/www/html/trabalho/googleAds/Api/src/libs/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201809/mcm/ManagedCustomerService.php(185 in /var/www/html/trabalho/googleAds/Api/src/libs/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php on line 43

**Comment by fiboknacky** [comment]
You get an [NOT_AUTHORIZED](https://developers.google.com/adwords/api/docs/reference/v201809/ManagedCustomerService.ManagedCustomerServiceError.Reason) error, probably because you have no sufficient permission to send this request.

As this is related to the AdWords API in general, please post your question on [its forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead.
Please note that attaching your full SOAP logs would speed up the investigation as well.

Cheers,
Knack
