### ISSUE TITLE
Incorrect type hinting on FieldPathElement

### ISSUE THREAD

**Issue by umbert-cobiro** [googleads/googleads-php-lib#662]
On the class `FieldPathElement` the `index` property is typehinted as `int` but the constructor defaults it to null.

The `getIndex` function does also have an incorrect type hinting derivated from it.

**Comment by fiboknacky** [comment]
What product are you using? AdManager or AdWords?

**Comment by umbert-cobiro** [comment]
Sorry for the late reply, I believe this issue was in AdWords

**Comment by fiboknacky** [comment]
Thanks for confirming.

> On the class FieldPathElement the index property is typehinted as int but the constructor defaults it to null.

I agree that to be more precise, it should have been `?int` instead of just `int`.
Unfortunately, we don't have bandwidth right now to fix that, and provided that it doesn't prevent us from using the library, we need to postpone fixing this for now.
(If it does prevent you from using this library in some way, please let us know)

> The getIndex function does also have an incorrect type hinting derivated from it.

For this, I don't see how it's incorrect. Could you elaborate?
