### ISSUE TITLE
1000 file limit on directories - Cannot deploy package on Google App Engine Standard

### ISSUE THREAD

**Issue by timothyasp** [googleads/googleads-php-lib#677]
Related Issue: https://issuetracker.google.com/issues/166773925

Attempting to deploy an existing project using this library to App Engine Standard.  The directories under `src/Google/AdsApi/AdManager` are all > 1k files, which is over the hard limit set by App Engine Standard.  

Example Directory: https://github.com/googleads/googleads-php-lib/tree/master/src/Google/AdsApi/AdManager/v202008

Is there a way to restructure or eliminate some files? 

I see that 3 years ago #397 was closed, but the issue remains.  

Thanks for your help!

**Comment by thangduo** [comment]
Hi Tim,

Thanks for reporting this issue. I didn't get a response to #397, that's why it got de-prioritized and closed.

In this client library, we generate one class per file to make it easy for developers to navigate the classes and auto loader to load the classes.

Currently, there are 1139 files under `/src/Google/AdsApi/AdManager/v202008/`. A work-around is to combine 151 files containing just the error classes, eg. `ActivityError.php`, `AdExclusionRuleError.php`, ..., `WorkflowValidationError.php`, into a single PHP file. However, you will have to modify the auto loader class to load the combined file in addition to other individual class files.

Can you please let us know whether this work-around would work for you?

Thanks,
Thang

**Comment by timothyasp** [comment]
Thanks for the reply and workaround - I ended up migrating off of App
engine due to this and other issues, so I don't have a way to test this,
but hopefully this will help someone else.
