### ISSUE TITLE
Deprecation for PHP 7.1 already?

### ISSUE THREAD

**Issue by WouterWidgets** [googleads/googleads-php-lib#693]
I'm using this package on a server that runs PHP 7.1 (and is not easily upgradable to a higher PHP version).

As far as I can tell, the highest version of this package that supports PHP 7.1 is `44.0`, but that version relies on AdManager `v201911`, which is not only deprecated but also disabled:

```
Uncaught Google\AdsApi\AdManager\v201911\ApiException: [ApiVersionError.UPDATE_TO_NEWER_VERSION @ version; trigger:'Version v201911 was deprecated and is now disabled. Please check the DoubleClick for Publishers blog for more information or contact us via the support forum.
```

Is there a way for me to target AdManager versions newer than `v201911` on PHP 7.1?

Regards, Wouter

**Comment by WouterWidgets** [comment]
Additional note: I'm running PHP 7.1.33, which is a little over a year old.

**Comment by thangduo** [comment]
Hi Wouter,

Thanks for your feedback.

The `ApiVersionError.UPDATE_TO_NEWER_VERSION` error is returned when your client program tries to reach a deprecated version of the Ad Manager API regardlessly of the PHP versions. Please refer to the Ad Manager API deprecation schedule for details: https://developers.google.com/ad-manager/api/deprecation

This client library cannot support PHP 7.1 because it reached the end of life more than a year ago (24 Oct 2019). Please refer to PHP supported versions for details: https://www.php.net/supported-versions.php


If you have to use PHP 7.1, you can try to download the latest version of this client library and change the required PHP version in the composer.json file to `"php": ">=7.1"` before running `composer install`. The changelog shows that it should be a straight forward action because it doesn't involve changing any other files: https://github.com/googleads/googleads-php-lib/commit/aaf27ec0a2ec2fe67192d813f5d67a678258940b

Thanks,
Thang
