### ISSUE TITLE
Declare technology providers in creative

### ISSUE THREAD

**Issue by richaudience** [googleads/googleads-php-lib#710]
Hi guys

How can I add technology providers to the creativities?
I've been looking for the method, but I haven't found it.

Cheers

**Comment by richaudience** [comment]
Can you give me your opinion on this? Thank you.
Best regards

**Comment by thangduo** [comment]
Hi,

This question is more appropriate for our [developer forum](https://groups.google.com/g/google-doubleclick-for-publishers-api) because it is not a PHP specific issue.

In general, you can read a list of default ThirdPartyDataDeclaration for your network via the [`getDefaultThirdPartyDataDeclaration()`](https://developers.google.com/ad-manager/api/reference/latest/NetworkService#getdefaultthirdpartydatadeclaration) of the `Network` service. Then, you can specify a creative's specific technology provider using the provider's ID using the [`thirdPartyDataDeclaration`](https://developers.google.com/ad-manager/api/reference/latest/CreativeService.Creative#thirdpartydatadeclaration) property of the `Creative` type.

Thanks,
Thang

**Comment by richaudience** [comment]
Okey! Thanks for you respone
