### ISSUE TITLE
Service account support

### ISSUE THREAD

**Issue by buley** [googleads/googleads-php-lib#77]
As of September [DFP supports service accounts](http://googleadsdeveloper.blogspot.com/2014/09/announcing-oauth-20-service-account.html). 

To my knowledge this is not yet supported in the PHP client. It would be awesome to see this support surfaced in a future version of the PHP client library. Among my personal reasons for this wishlist item, it would circumvent the need for the refresh token dance.

**Comment by vtsao** [comment]
Hi, that's correct, we currently do not support OAuth2 service accounts in this client library. We do plan to eventually swap out our current OAuth2 client with another one that has support for service accounts, so it's definitely on our roadmap.

Also, for the current way we recommend doing things, you only need to do the refresh token dance once if you request an offline refresh token, so it's not significantly more overhead than using a service account.

**Comment by mbardelmeijer** [comment]
:+1:

**Comment by vtsao** [comment]
The beta version of this client library now uses the [Google Auth PHP library](https://github.com/google/google-auth-library-php), instead of this library having its own OAuth2 code. That OAuth2 library supports service accounts (JSON key files). Thus, you can now use service accounts with the beta version of this library.

[This wiki page](https://github.com/googleads/googleads-php-lib/wiki/%5BEXPERIMENTAL-BRANCH%5D-API-access-using-own-credentials-(server-to-server-flow)) explains how to use them with the beta version of this library.

We won't be adding any OAuth2 features to the current client library as we're focusing efforts on getting the beta version to stable). Please check out the beta [changelog](https://github.com/googleads/googleads-php-lib/blob/experimental/CHANGELOG.md) for details.
