### ISSUE TITLE
Getting blank screen GetRefreshToken.php

### ISSUE THREAD

**Issue by MrDarpan** [googleads/googleads-php-lib#97]
I followed Getting started tutorial and when I am trying to get refresh token I am only getting blank page nothing happened not even error just a blank page. I run example and other php files every file giving me blank page.

Anyone please tell me what is the problem?

I am on localhost and using adwords

**Comment by vtsao** [comment]
All of our examples are meant to be run via the command line and not a web browser/page. We'll make a note to clarify that in our README and/or the example comments.

**Comment by MrDarpan** [comment]
I want to use this lib in my web application, if these examples are ment to be run via command line then is there any alternative or tutorial for this to run via web browser? I am new to AdWords..

**Comment by vtsao** [comment]
The GetRefreshToken example must be run via the command line since it requires user input and is a one-time setup step. It is a helper example for you to get your OAuth2 offline refresh token.

The rest of the examples should work in a web application, but you may need to tweak some things, such  as printing output to the webpage instead of STDOUT.

**Comment by alancoleman** [comment]
If you're starting out then Ewan Heming posted an excellent article about how to use OAuth 2 with the AdWords API - http://www.ewanheming.com/adwords-api-oauth-tutorial

Also, if you're running the example pages individually, you'll need to code out the return to display the results in browser....
```
// Don't run the example if the file is being included.
if (__FILE__ != realpath($_SERVER['PHP_SELF'])) {
	//return;
}
```
